### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by cyb3rw0lf** [wustep/github-project-exporter#1]
I tried this script but always get  **[error] The resource you requested was not found!**
![image](https://user-images.githubusercontent.com/25265715/130242630-8de64034-72bd-4281-93e7-81c23130b4bd.png)

**Comment by wustep** [comment]
Hey @cyb3rw0lf -- this still works for me! Maybe the inputs are wrong or the access token was misconfigured? 

![image](https://user-images.githubusercontent.com/6259534/130292057-b0cbd326-d48e-4084-b2a0-fc432c39027a.png)

![Screen Shot 2021-08-20 at 2 02 23 PM](https://user-images.githubusercontent.com/6259534/130293037-5ea70a22-d0e8-4d8c-bfb6-91fde61cd5c0.png)

Edit: Oh wait! I think I see it. Your repo name includes the full link of what you want to export. Just have the repo itself (e.g. "github-project-exporter")

LMK if that works!

**Comment by wustep** [comment]
Oops, actually I do repro this when I try with yarn (and when I use npm it doesn't create the file). Hmm strange. Will see if I can figure it out this weekend.

**Comment by rich-bg** [comment]
Looks like it has a cap of 30 issues per type when I run it. (E.g. if I have 40 new issues, it will only pull 30)

**Comment by wustep** [comment]
@rich-bg 

ooh, looks like a GitHub enforced limit per-page is 100 and 30 by default. I can add pagination later but in the meantime you can add the per_page parameter in GitHub.js to bump the 30 to 100.

https://docs.github.com/en/rest/reference/projects#list-project-cards--parameters

**Comment by rich-bg** [comment]
Ah yeah.

Added a simple return await this.get(`projects/columns/${columnId}/cards?per_page=100 and it works :)

Thanks!

**Comment by wustep** [comment]
Thanks Angripo for implementing pagination in #2!
