### ISSUE TITLE
Feature request.  Issue number in the export

### ISSUE THREAD

**Issue by mreekie** [wustep/github-project-exporter#4]
Description:
 Would it be possible to include the issue number as a column in the export?

Use case: 
I _need_ the "task status" column from the GitHub Project that I manage to be sync'd into Asana for each GitHub issue

Going in::
 - I have to use Asana for PM work
 - The devs have to use github.
 - I use unito to synch GitHub and Asana
 - Unito cannot sync GitHub project information with Asana. Specifically I need to know the column in the GitHub project that the issue is in
 - Unito can sync between Asana and google sheets
 
what happens:
- I export the GitHub project to csv using github-project-exporter
- copy the output to a google docs spreadsheet into tab1

- separately I synchronize those same issues from Asana into tab2 in the same spreadsheet

-  Using **the issue number** which would be both on tab1 and on tab2, I can update a column "Task Status" on tab2 
-  Any row which has changed it's "Task Status" based on the info on tab1, will be updated back to Asana by unito.

p.s. I've wanted/needed the ability to dump a project as opposed to the repo for a loooong time. Thank you for making this tool.

**Comment by wustep** [comment]
hiya @mreekie! i'm glad people are using this :)

based on the [API wiki](https://docs.github.com/en/rest/reference/issues)

I think it's just a matter of adding issue_number here to [main.js](https://github.com/wustep/github-project-exporter/blob/main/main.js#L118-139). 
```
          issueFields = {
            issue_number: issue.number, // <---- add this line!
            issue_state: issue.state,
            issue_labels: issue.labels.length
              ? issue.labels.reduce((labelString, label) => {
                  return labelString === null
                    ? label.name
                    : labelString + ", " + label.name;
                }, null)
              : undefined,
            issue_link: issue.html_url, // This is either the PR request (if exists) or issue
            issue_body: issue.body,
            issue_assignees: issue.assignees.length
              ? issue.assignees.reduce((assigneeString, assignee) => {
                  return assigneeString === null
                    ? assignee.login
                    : assigneeString + ", " + assignee.login;
                }, null)
              : undefined,
            issue_created_at: issue.created_at,
            issue_updated_at: issue.updated_at,
            issue_closed_at: issue.closed_at,
          };
 ```

I can get to this eventually, but feel free to try this and submit a PR!

**Comment by mreekie** [comment]
I'm not a programmer but I'll give it a shot!

**Comment by wustep** [comment]
Added in latest commit! Thanks for the suggestion :). Let me know if it works.

https://github.com/wustep/github-project-exporter/commit/6fef0a91c010587dba17cffbc6efb32a67120078

**Comment by mikeaintworkin** [comment]
I'm finally revisiting your project.
I think I may need it for  some reporting I'm working on.
I came back to look and found you had incorporated this info.
Thank you!
