### ISSUE TITLE
New ProjectV2 exporter

### ISSUE THREAD

**Issue by justinmahar** [wustep/github-project-exporter#6]
Looks like this project is only compatible with classic GitHub projects which uses a deprecated REST API.

I learned how to use the newer GraphQL API and created a new CSV exporter that supports ProjectsV2.

Anyone looking for an exporter for newer projects can try it here:

**Comment by justinmahar** [comment]
@wustep I added a link to your project from my README for people with classic projects. Maybe add a link to my ProjectV2 exporter to your README so people can find it?

**Comment by wustep** [comment]
Sure thing! Thanks for the info, didn't realize there was a V2 :)
